language: go
os: linux
dist: bionic
go: 1.15.x

env:
  - GOPRIVATE=github.com/qadre

stages:
  - test

jobs:
  - stage: test
    before_install:
      - chmod +x .travis/build-condition.sh
      - git config --global url."https://qadrebot:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"
    install: true
    before_script:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
    script: make ci
    after_success:
      - bash <(curl -s https://codecov.io/bash)
